version: "3.8"
services:

  dbMysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    container_name: ${MYSQL_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    command:
      - "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./SQL/setup.sql:/docker-entrypoint-initdb.d/setup.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    links:
      - dbMysql
    depends_on:
      - dbMysql

  web:
    build: ./docker
    ports:
      - "8910:8910"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    links:
      - dbMysql
    depends_on:
      - dbMysql
      - adminer

  redis:
    image: "redis:alpine"