<p>
    <label for="User">User : <?php echo $userName; ?></label>
    <?php var_dump($userName);?>
</p>
<center>

    <h2>Sign up using this form</h2>

    <?php echo $this->tag->form("signup/signup"); ?>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("Sign up"); ?>
    </p>

        </form>



    <?php
    echo "<br/>";
    echo $this->tag->linkTo(["register", "Register user", 'class' => 'btn btn-primary']);
    echo $this->tag->linkTo(["index", "Back to main page", 'class' => 'btn btn-primary']);
    echo $this->tag->linkTo(["signup/logout", "Logout", 'class' => 'btn btn-primary']);
    echo PHP_EOL; //novy radek
    //var_dump($userAdmin);

    if ($users->count() > 0 && $userAdmin) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>id</th>
            <th>Name</th>
            <th>Email</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Users quantity: <?php echo $users->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($users as $user) { ?>
            <tr>
                <td><?php echo $user->id; ?></td>
                <td><?php echo $user->name; ?></td>
                <td><?php echo $user->email; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}
?>
</center>