<h2>Register using this form</h2>

<?php echo $this->tag->form("register/register"); ?>

<p>
    <label for="name">Name</label>
    <?php echo $this->tag->textField("name"); ?>
</p>

<p>
    <label for="email">E-Mail</label>
    <?php echo $this->tag->textField("email"); ?>
</p>

<p>
    <?php echo $this->tag->submitButton("Register"); ?>
</p>

</form>

<?php
echo $this->tag->linkTo(["signup", "Back to sign up page", 'class' => 'btn btn-primary']);
?>